site_name: Terraform Learning Notes

nav:
  - Home: index.md
  - Terraform:
      - Basics: terraform-basics.md
      - Providers: providers.md
      - Variables: variables.md
      - State: state.md
      - Modules: modules.md

theme:
  name: material
